version: '3.5'
services:
  jekyll:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kadasterdst.azurecr.io/jekyll-serve:latest
    volumes:
      - .:/site
    ports:
      - '4000:4000'
    environment:
      - JEKYLL_BUILD_REVISION=local